
    <section>
        <h1>Let's begin:</h1>
        
        <p>The Twitter API allows you to track basic information about the 
           people that any specific twitter user follows.  So which Twitter user 
           would you like to see (hint: try yourself)?</p>

        <?php echo $this->form . "\n"; ?>
        
        <p><strong>Note:</strong> This could take awhile, just let it run.  
        The time this takes is directly proportional to the amount of data that
        is already cached.</p>
    </section>
