<?php echo $this->doctype('HTML5') . "\n"; ?>
<html>
<head>
    <?php echo $this->headTitle('Exodus') . "\n"; ?>
    <?php echo $this->headLink()->prependStylesheet('/lib/css/screen.css') . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
</head>
<body>
    
    <header>
        <hgroup>
            <h1><a href="/">Exodus</a></h1>
            <h2>&raquo; control your connections</h2>
        </hgroup>
    </header>

    <?php echo $this->layout()->content . PHP_EOL ?>
    
    <footer>
        <span class="author">Created by <a href="http://epixa.com">Court Ewing</a></span>
        &middot;
        <span class="host">Hosted on <a href="http://orchestra.io">Orchestra.io</a></span>
    </footer>
    
</body>
</html>