<?php echo $this->doctype('HTML5') . "\n"; ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
    <?php echo $this->headTitle('Exodus') . "\n"; ?>
    <?php echo $this->headLink()->prependStylesheet('/lib/css/screen.css?1300481247') . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
    
    <?php echo $this->render('partials/analytics.phtml'); ?>
    
    <!--[if lte IE 8]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
    <!--[if lte IE 8]>
    <noscript>
         <strong>Warning!</strong>
         Because your browser does not support HTML5, some elements are 
         simulated using Javascript.  Unfortunately your browser has disabled
         scripting. Please enable it in order to render this page.
    </noscript>
    <![endif]-->
    
    <header>
        <hgroup>
            <h1><a href="/">Exodus</a></h1>
            <h2>&raquo; control your connections</h2>
        </hgroup>
    </header>

    <?php echo $this->layout()->content . PHP_EOL ?>
    
    <footer>
        <span class="author">Created by <a href="http://epixa.com">Court Ewing</a></span>
        &middot;
        <span class="host">Hosted on <a href="http://orchestra.io">Orchestra.io</a></span>
    </footer>
    
</body>
</html>