
    <section>
        <p>On March 11th, Twitter sent ripples through their developer community
           when they created a post on their mailing list that implied that the 
           free-spirit and lax guidelines that the community is used to were 
           going by the wayside.  Regardless of your interpretation or feelings 
           on the matter, I think we can all agree that user connections should 
           not be bound by any particular service.</p>
        
        <p>Exodus allows users to see which of the people they follow on twitter
           also have accounts on identi.ca.</p>
        
        <p>In the near future, it is my hope to also implement the comparison in 
           reverse, so existing identi.ca users can see which of the people they
           subscribe to are also on twitter.</p>
        
        <p><a href="<?php echo $this->url(array(), 'begin', true); ?>">Let's get started, shall we?</a></p>
    </section>
